owner: Truyoladm # GitHub username
repo: upptime # GitHub repository name

sites: # List of endpoints to track
  - name: Truyol
    url: https://www.truyol.com
  - name: Bo Truyol
    url: https://bo.truyol.com/bo/acceso
  - name: Blog Truyol
    url: https://truyol.com/blog/
    
assignees: # Users to assign downtime issues (optional)
  - Truyoladm
status-website: # Status website (optional)
  #cname: upptime.js.org # Custom domain CNAME
  logoUrl: https://truyol.com/img/es/logo/truyol.png
  name: Upptime Truyol
  introTitle: "**Upptime** TRUYOL"
  introMessage: Aqui podras comprobar el Estado de Truyol.
  #cname: demo.upptime.js.org
  #cname: truyoladm.github.io  
  baseUrl: /upptime
  #name: Upptime # Status website title

navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
      
      
workflowSchedule:
  graphs: "0 */6 * * *"
  responseTime: "10 */6 * * *"
  staticSite: "20 */6 * * *"
  summary: "30 */6 * * *"
  updateTemplate: "0 0 * * *"
  updates: "40 */6 * * *"
  uptime: "*/5 * * * *"

 
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
