owner: Truyoladm # GitHub username
repo: upptime # GitHub repository name

sites: # List of endpoints to track
  - name: Truyol
    url: https://www.truyol.com
  - name: Bo Truyol
    url: https://www.bo.truyol.com
  - name: Blog Truyol
    url: https://www.blog.truyol.com
    
assignees: # Users to assign downtime issues (optional)
  - Truyoladm
status-website: # Status website (optional)
  #cname: upptime.js.org # Custom domain CNAME
  baseUrl: /upptime
  name: Upptime # Status website title

navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
